# Generated by Django 4.2.4 on 2023-08-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Project Title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        default="Some quick example text to build on the card title and make up the bulk of the card's content.",
                        max_length=1000,
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        default="Click the below button and Explore more about the website.",
                        max_length=1000,
                    ),
                ),
                ("btn", models.CharField(default="Go somewhere", max_length=100)),
                (
                    "url",
                    models.URLField(default="https://debasishmohanta.netlify.app/"),
                ),
                ("image", models.IntegerField()),
            ],
        ),
    ]
